### ISSUE TITLE
Production ready boilerplate?

### ISSUE THREAD

**Issue by automaciej** [mrd0ll4r/tbotapi#15]
_(I don't know how to start a discussion so I opened in issue, is there a better way?)_

I looked at the example directory, and the boilerplate.go file comments say that this code is not to be used in production. I looked around, and found no example of what would be a production-ready code. Could you provide such an example? Or explain what features are needed?

**Comment by mrd0ll4r** [comment]
Hey, issues are fine. I also always idle in #tbotapi on freenode.

About the boilerplate code:
- I have never tested the webhook version
- It needs proper error handling in case getting an update failed
- The bots need proper error handling in case sending a message failed
- There is a lot of verbose logging going on sometimes
- The handling of messages is synchronous, i.e. in the same goroutine that receives updates on the updates channel (easy to fix. Note that since resty recently introduced a global lock, requests will not actually be sent in parallel. But handling a message concurrently should still save a good amount of time.)

I did think of one clever thing when writing the boilerplate: The bot may or may not be part of a bigger program, that's why stopping is done via the `closing` channel. It is currently closed when we receive a signal, but that could be changed to whatever you need.

I cleaned up the boilerplate code a bit just now, fyi.

EDIT:
Generally, independent of the boilerplate, the most dangerous thing about this library is that I implemented all optional message fields as pointers. In retrospect I should have made message a marker interface and each type of message its own struct, so users would _have_ to typeswitch to determine the type of the message. It is pretty easy to stumble across nil pointers now, because I didn't. I did add a `Type` method on messages to make switching over the type somewhat easy, but you have to be careful what fields of the message you access later.

Also this library is always a bit behind the official API. There are at least two other go wrappers for the API out there that might be more up-to-date.

**Comment by mrd0ll4r** [comment]
Closing, library no longer maintained.
